version: '3'

services:
  
  chat-server:
    image: chat-server
    build:
        context: ./
        dockerfile: Dockerfile
    expose:
      - "33000"
    environment:
      - host=chat-server
      - port=33000
      - redis=redis,port:6379,password=Redis2020!
      - mongoDbConnection=mongodb://root:MongoDB2020!@mongodb
      - mongoDbDatabase=take
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb
      - redis
      
  redis:
    image: redis
    command: redis-server --requirepass Redis2020!
    ports:
      - "6379:6379"
    networks:
      - mongo-compose-network
      
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2020!
    ports:
      - "27017:27017"
    volumes:
      - ./Chat.Server.Data.MongoDb.Volume/:/data/db
    networks:
      - mongo-compose-network
            
  load-balancer:
    image: nginx:latest
    volumes:
      - ./Chat.Server.LoadBalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mongo-compose-network
    depends_on:
      - chat-server
    ports:
      - "34000:34000"
      
networks: 
    mongo-compose-network:
      driver: bridge